### PR TITLE
ALL: no ganesha packages for now

### PR DESCRIPTION
**Pull request by liewegas**
Signed-off-by: Sage Weil <sage@redhat.com>

### CODE REVIEW

**Comment by liewegas** [comment]
This matches the empty file in the ``master`` dir.  What's weird is that I do'nt see ganesha packages defined for nautilus or most of hte other targets.. i'm not sure where the list is coming from.  In any case, though, I think this will fix our ceph-ci.git container builds

**Comment by dsavineau** [comment]
> This matches the empty file in the `master` dir. What's weird is that I do'nt see ganesha packages defined for nautilus or most of hte other targets.. i'm not sure where the list is coming from. In any case, though, I think this will fix our ceph-ci.git container builds

https://github.com/ceph/ceph-container/blob/master/src/daemon-base/__GANESHA_PACKAGES__

I suppose the issue is when using ceph branches like "wip*" ?

Because right now the fix proposed breaks nautilus, mimic and luminous releases.

We should probably do the opposite thing:
  - create `ceph-releases/{nautilus,mimic,luminous}/daemon-base/__GANESHA_PACKAGES__` with the content of `src/daemon-base/__GANESHA_PACKAGES__`
  - remove `ceph-releases/master/daemon-base/__GANESHA_PACKAGES__`
  - empty `src/daemon-base/__GANESHA_PACKAGES__`

**Comment by liewegas** [comment]
Like so?

**Comment by dsavineau** [comment]
> Like so?

Yes this should fix the ganshe issue but considering that there's other stuff using `ceph-releases/master` [1] I think the wip branches will still be broken.

I guess a better approach for all of this would be to set the content not for a ceph release but for the centos 8 release instead.
That way it will work for both master and wip* branches.

[1] https://github.com/ceph/ceph-container/tree/master/ceph-releases/master

**Comment by liewegas** [comment]
Can we merge this in the meantime and hopefully i'll get a working wip-* build?

**Comment by liewegas** [comment]
For wip, the other thing to keep in mind is that we really want any unrecognized branch (master, wip-*) to use the 'master' release.  Then nautilus or *nautilus (e.g., wip-foo-nautilus) shoudl use nautilus.  ANd wip-*-mimic should use mimic.. etc.

**Pull request closed without merging**
