### PR TITLE
centos: Disable Ganesha

### PR DESCRIPTION
**Pull request by ErwanAliasr1**
As per Ken Dreyer message on ceph-devel, let's disable Ganesha temporarily.

    Hi folks,
    The latest nfs-ganesha RPMs are gone from http://download.ceph.com
    I want to build these in http://cbs.centos.org/koji/ instead, so I'm working through that on centos-devel@centos.org.
    Eventually I plan to build all the RPMs we need for nautilus there.

This commit will have to be reverted once the new repository will be ready.

Signed-off-by: Erwan Velu <evelu@redhat.com>

Description of your changes:

Which issue is resolved by this Pull Request:
Resolves #

Checklist:
- [ ] Documentation has been updated, if necessary.
- [ ] Pending release notes updated with breaking and/or notable changes, if necessary.

### CODE REVIEW

**Comment by ktdreyer** [comment]
@tserlin I'd like to work with you to get nfs-ganesha built in CBS for nautilus and luminous.

**Comment by tserlin** [comment]
@ErwanAliasr1 Luminous RPMs are now there:

http://download.ceph.com/nfs-ganesha/rpm-V2.7-stable/luminous/

**Comment by ErwanAliasr1** [comment]
Cool. Can we get the aarch ones also ? That would allow a complete return
to nominal support. Thx for your help !

**Comment by tserlin** [comment]
It looks like we never built on aarch64 before (despite the directory being there)... I can check.

**Comment by ErwanAliasr1** [comment]
Any ETA for having CBS featuring all the ganesha packages ?

**Comment by ErwanAliasr1** [comment]
When I build the images, I have the following error.
Is there any metadata issue ? Can you update them if so ?
The suggested action to clean the metadata doesn't make sense in my case since the repo is just added before during the container build. So there is no chance of having older metadata here.

Downloading packages:
http://download.ceph.com/nfs-ganesha/rpm-V2.7-stable/mimic/x86_64/libntirpc-1.7.1-0.1.el7.x86_64.rpm: [Errno -1] Package does not match intended download. Suggestion: run yum --enablerepo=ganesha clean metadata
Trying other mirror.
http://download.ceph.com/nfs-ganesha/rpm-V2.7-stable/mimic/x86_64/nfs-ganesha-2.7.1-0.1.el7.x86_64.rpm: [Errno -1] Package does not match intended download. Suggestion: run yum --enablerepo=ganesha clean metadata
Trying other mirror.
http://download.ceph.com/nfs-ganesha/rpm-V2.7-stable/mimic/x86_64/nfs-ganesha-rgw-2.7.1-0.1.el7.x86_64.rpm: [Errno -1] Package does not match intended download. Suggestion: run yum --enablerepo=ganesha clean metadata
Trying other mirror.
http://download.ceph.com/nfs-ganesha/rpm-V2.7-stable/mimic/x86_64/nfs-ganesha-ceph-2.7.1-0.1.el7.x86_64.rpm: [Errno -1] Package does not match intended download. Suggestion: run yum --enablerepo=ganesha clean metadata
Trying other mirror.

**Comment by tserlin** [comment]
@ErwanAliasr1 Yes, there was some weird issue when creating the yum repo (still looking into that). I've manually run "createrepo" to fix. Seems to work for me now.

**Pull request merged**
