### PR TITLE
ubi9: split based on the branding

### PR DESCRIPTION
**Pull request by guits**
this splits ubi9 by creating `ceph-releases/<ceph-release>/ubi9-<branding>`
given that quincy and reef are both based on ubi9 and require ceph release
specific changes.

Signed-off-by: Guillaume Abrioux <gabrioux@ibm.com>

### CODE REVIEW

**Comment by ktdreyer** [comment]
This reverts some of the change in https://github.com/ceph/ceph-container/pull/2122 where I removed the individual tags for each image. As one example, `sed` now searches for the `v4.10` tag (and it should not. `cephadm` uses `v4.12` now):

```diff
-  -e "s|registry.redhat.io/openshift4/ose-prometheus:|cp.icr.io/cp/ibm-ceph/prometheus:|" \
+  -e "s|registry.redhat.io/openshift4/ose-prometheus:v4.10|cp.icr.io/cp/ibm-ceph/prometheus:v4.10|" \
```

We already line up image tags between IBM and Red Hat's products. It's simpler and more future-proof to only replace the image URLs without touching the tags.

**Comment by guits** [comment]
@ktdreyer I've updated the branch, your comment should be addressed.

**Review by ktdreyer — CHANGES_REQUESTED** [review]
I've composed the `main` branch, and then diff'd that against this PR's output.

Here are the changes this PR makes:

```diff
-  -e "s|registry.redhat.io/rhceph/rhceph-6-rhel9:|cp.icr.io/cp/ibm-ceph/ceph-6-rhel9:|" \
+  -e "s|registry.redhat.io/rhceph/rhceph-7-rhel9:latest|cp.icr.io/cp/ibm-ceph/ceph-7-rhel9:latest|" \
   -e "s|registry.redhat.io/openshift4/ose-prometheus:|cp.icr.io/cp/ibm-ceph/prometheus:|" \
-  -e "s|registry.redhat.io/openshift-logging/logging-loki-rhel8:|cp.icr.io/cp/ibm-ceph/logging-loki-rhel8:|" \
-  -e "s|registry.redhat.io/rhceph/rhceph-promtail-rhel9:|cp.icr.io/cp/ibm-ceph/promtail-rhel9:|" \
   -e "s|registry.redhat.io/openshift4/ose-prometheus-node-exporter:|cp.icr.io/cp/ibm-ceph/prometheus-node-exporter:|" \
-  -e "s|registry.redhat.io/rhceph/rhceph-6-dashboard-rhel9:|cp.icr.io/cp/ibm-ceph/ceph-6-dashboard-rhel9:|" \
+  -e "s|registry.redhat.io/rhceph/rhceph-7-dashboard-rhel9:latest|cp.icr.io/cp/ibm-ceph/ceph-7-dashboard-rhel9:latest|" \
   -e "s|registry.redhat.io/openshift4/ose-prometheus-alertmanager:|cp.icr.io/cp/ibm-ceph/prometheus-alertmanager:|" \
-  -e "s|registry.redhat.io/rhceph/rhceph-haproxy-rhel9:|cp.icr.io/cp/ibm-ceph/haproxy-rhel9:|" \
-  -e "s|registry.redhat.io/rhceph/keepalived-rhel9:|cp.icr.io/cp/ibm-ceph/keepalived-rhel9:|" \
-  -e "s|registry.redhat.io/rhceph/snmp-notifier-rhel9:|cp.icr.io/cp/ibm-ceph/snmp-notifier-rhel9:|" \
+  -e "s|registry.redhat.io/rhceph/rhceph-haproxy-rhel9:latest|cp.icr.io/cp/ibm-ceph/haproxy-rhel9:latest|" \
+  -e "s|registry.redhat.io/rhceph/keepalived-rhel9:latest|cp.icr.io/cp/ibm-ceph/keepalived-rhel9:latest|" \
+  -e "s|registry.redhat.io/rhceph/snmp-notifier-rhel9:latest|cp.icr.io/cp/ibm-ceph/snmp-notifier-rhel9:latest|" \
```

Here are the remaining changes we need:
- [ ] Please remove all references to the `latest` tag from this `sed` command. It should be the way we set it up in https://github.com/ceph/ceph-container/pull/2122 
- [ ] Please add `loki` and `promtail` back - not sure why these are gone in this latest version?

We should only see `6` changing to `7`, not these other changes.

We do need to rename the grafana container for `7`, but I can submit a separate PR for that after we finish this one.

**Comment by ktdreyer** [comment]
The steps I used to test this:

1. Run `BRANDING=ibm VERSION=7 ./contrib/compose-rhcs.sh` on the `main` branch
2. Set that `composed` output aside somewhere (like with `cp`)
3. Switch from `main` to this PR's branch (`quick-clean-up`)
4. Run `BRANDING=ibm VERSION=7 ./contrib/compose-rhcs.sh` again, this time on the `quick-clean-up` branch
5. Compare that output to the output from `main`

With the latest updates, this PR now shows the correct diff (just changing `6` to `7`).

**Review by ktdreyer — APPROVED** [review]

**Pull request merged**
