### PR TITLE
Integrating #905 and #923 for preparing the merge

### PR DESCRIPTION
**Pull request by ErwanAliasr1**
This PR superseed #905 and #923.

This PR is about reworking the "Build Ubuntu" & "Remove old ceph-releases dir" commits which were doing a cp/rm into of git mv/git rm.

In addition, the Centos port is added on top.

This branch is fast forward on master and integrates all the code of those two PRs.

It have been tested successfully on all flavors.

### CODE REVIEW

**Comment by ErwanAliasr1** [comment]
@leseb for me the PR is over.
All the images builds fine except luminous on centos because of a broken package which is about to be fixed.

LGTM !

**Comment by BlaineEXE** [comment]
lease add signed-off-by lines to commits you have modified/added, and I would appreciate that if you haven't modified one of my commits yourself that you are not listed in the commit metadata as an author.

**Comment by BlaineEXE** [comment]
"final integration" is not a descriptive PR name

**Comment by BlaineEXE** [comment]
I think we should separate the Ubuntu and CentOS contributions into separate PRs. Ubuntu is the core and minimum required functionally for this project. Adding CentOS as well without adding all other distros is breaking the smallest-possible-change goal of an already massive pull request.

**Comment by BlaineEXE** [comment]
Since I'll be returning to work soon, I'd much rather reopen my original pr and continue to take feedback there. I think the scope of this change is creeping too much, and there have already been several people concerned about the sheer size of even the minimal-est change.

**Comment by ErwanAliasr1** [comment]
@BlaineEXE if you can you irc for a short talk that would be fantastic. I'd love to clarify my intention and insure you don't take this PR aggressively against your work.

**Comment by BlaineEXE** [comment]
I'm commenting from my phone in between vacation things. I don't think I'm taking things aggressively, but I am really concerned about feature creep (CentOS support on top), and I would like to make sure the commits are clean and squashed into the appropriate places. 

I think our discussion about the GENERIC_ARCH has exposed a hidden assumption from the initial design of the flavor specification that's worth more discussion. Specifically, I think we want to make it clear that ARCH in our case is Ceph arch, and we should compute the GO_ARCH accordingly for getting golang packages. I'm not sure if we should compute go arch in Python or in the Makefile. It should be easy to add new ceph-arch->go-arch pairs. I think that's a really important idea for our builds that we haven't been as explicit about as we can be.

**Comment by BlaineEXE** [comment]
In this PR, the commit author for "Build Ubuntu images for supported ceph versions" no longer shows me as an author in the metadata, and as this represents the majority of my personal contributions to this effort, I do expect proper credit.

**Comment by ErwanAliasr1** [comment]
@BlaineEXE you are _perfectly_ right  about GENERIC_ARCH.
I was miseladed by the arch and yes my commit is unncessary.
I removed it.

**Comment by ErwanAliasr1** [comment]
@BlaineEXE I didn't meant to steal any authorship. We needed to update this commit to switch for a massive "shell rm/cp" into a "git mv/rm". So performing that task needed another commit and wanted to "accelerate" the process while you were in holidays.
Yes it put me as author. To clarify that, and as per https://help.github.com/articles/creating-a-commit-with-multiple-authors/, I just updated the commit with a co authorship.
By the past, part of some of my commits/ideas were integrated without I felt "loosing" my authorship.
I hope the co-author is ok for you.

**Comment by ErwanAliasr1** [comment]
@BlaineEXE even better, put it you back as the author & myself as co-author.

**Comment by ErwanAliasr1** [comment]
@BlaineEXE I think we have reached a good state here.
Integrating centos in this PR isn't that scary as long a the code is very light and the number of commits reduced. That's an easier way to test the two already done ports aka ubuntu + centos.
I'd appreciate if you can +1 for the merge. It's maybe not 100% perfect but it's good enough for being merged and complete the CI integration.

**Comment by BlaineEXE** [comment]
I'd like to do the ARCH/GO_ARCH work I mentioned.

**Comment by ErwanAliasr1** [comment]
@BlaineEXE is that a show-stopper or could it be added later ?

**Comment by BlaineEXE** [comment]
I've been thinking about the author+coauthorship situation, and I feel good about having you as co-author on the commit that you fixed (Ubuntu support) as well as readme additions since you provided a lot of great feedback, support, and ideas for both; however, my contributions in this PR represent nearly 200 hours of work including my evenings, weekends, and vacation time, and I would appreciate leaving the remaining commits with the authorship unmodified.

**Comment by BlaineEXE** [comment]
As for the ARCH work, I think we can do it later after discussing what our arch strategy is.

**Comment by ErwanAliasr1** [comment]
@BlaineEXE " I would appreciate leaving the remaining commits with the authorship unmodified."

I told you that in private already but state here publicly. You did an awesome work, we do acknowledge & recognize it. Don't worry about the authorship. All commits will remain yours except the one I directly worked on as you mentioned. For the light updates I performed today (like removing white spaces, I didn't changed anything regarding authoring).

I hope I adressed all your remaining points here so we can go forward & make it happen by having a merge.

Cheers,

**Comment by ErwanAliasr1** [comment]
@BlaineEXE ack for merge ?

**Comment by BlaineEXE** [comment]
I think there are a handful of things I mentioned that should be cleaned up, but looks good after those.

**Comment by ErwanAliasr1** [comment]
@BlaineEXE looks good for you ?

/me is crossing fingers firmely :)

**Comment by BlaineEXE** [comment]
I think what we talked about LGTM. Like leseb said, it doesn't have to be perfect, and I think we've actually got a really great foundation here, and I'm two thumbs up to merge. I'm proud of what we were able to design together. Thanks for your hard work and late nights. 😊

-----

Topics I've mentally noted for later discussion, just to make sure nothing gets lost. Not all of these are fully-fledged thoughts. Please add your own thoughts to this too.
- refine our definition of ARCH and talk about calculated GO_ARCH
- What flavors do we want for default builds?
- revisit cleanup operations to make sure we aren't shooting ourselves in the foot by being too aggressive (p.s., I did a little bit of digging here looking at docker image layers)
- I haven't mentioned this, but introduce an environment variable like CEPH_VERSION_NUMBER in case we want to execute code paths conditionally for Ceph versions lt/gt rather than just by name. This will help us avoid the situation we have with jewel/kraken where we have unique, slightly modified source files in the ceph-releases tree. I see this as something we want to do for luminous+ but needn't refactor jewel/kraken.
- do we want to remove the blacklist functionality? It might be unnecessary.
- already has an issue created: use --squash build flag when it's officially supported by docker, and we can then add more image layers to make Dockerfiles easier to read and have more reuse of cached layers
- I think we could consider splitting the current readme into readme.md and developer.md. Worth it?
- Add a pull request template with a checklist that includes things like: update list of all flavors in Makefile if applicable, update readme if applicable, update script help text if applicable, update tests, passes linting tests, etc.
- on that note, more linting tests
- I'd like to understand more about the functional testing; I'd like to be able to add openSUSE CI to the project if that's desirable, and I want to make sure we have good test coverage overall
- coordinate with Rook to start using Ceph-container as Rook's base
- ... Other stuff I'm sure I forgot

**Comment by ErwanAliasr1** [comment]
@BlaineEXE can you switch your review to "approve" ?

**Comment by BlaineEXE** [comment]
Can I just say LGTM! ? GitHub on mobile is hard...

**Comment by ErwanAliasr1** [comment]
@BlaineEXE For sure, yes ! Thanks.

**Pull request merged**
