### PR TITLE
base: remove lang.sh

### PR DESCRIPTION
**Pull request by leseb**
When entering the container we always get this annoying warning:

bash: warning: setlocale: LC_CTYPE: cannot change locale (en_US.UTF-8): No such file or directory
bash: warning: setlocale: LC_COLLATE: cannot change locale (en_US.UTF-8): No such file or directory
bash: warning: setlocale: LC_MESSAGES: cannot change locale (en_US.UTF-8): No such file or directory
bash: warning: setlocale: LC_NUMERIC: cannot change locale (en_US.UTF-8): No such file or directory
bash: warning: setlocale: LC_TIME: cannot change locale (en_US.UTF-8): No such file or directory

Because the locale is not available, to fix this issue let's remove the
lang file which contains the local to set.

Signed-off-by: Sébastien Han <seb@redhat.com>

### CODE REVIEW

**Comment by leseb** [comment]
@dsavineau done.

**Comment by dsavineau** [comment]
@leseb not rhel 7?

**Comment by leseb** [comment]
@dsavineau done.

**Comment by ktdreyer** [comment]
@dsavineau thank you very much for tracking the equivalent RHEL fix. It really helps to keep downstream and upstream in sync when you do that.

Here is a syntax fix for this change: https://github.com/ceph/ceph-container/pull/1341

**Pull request merged**
