### PR TITLE
Add dashboard mgr module by default

### PR DESCRIPTION
**Pull request by jtlayton**
rook expects the dashboard to be available.

Signed-off-by: Jeff Layton <jlayton@redhat.com>

### CODE REVIEW

**Comment by leseb** [comment]
@jtlayton is it true for all the Ceph releases? Or only Nautilus?

**Comment by jtlayton** [comment]
Nautilus and up. The splitout of mgr modules was just done recently in nautilus.

**Comment by leseb** [comment]
So basically if we put this in `src/daemon-base/` this will affect all the daemons, that's a problem.

**Comment by jtlayton** [comment]
We already have override files for luminous and mimic:

ceph-releases/luminous/daemon-base/__CEPH_MGR_PACKAGE__
ceph-releases/mimic/daemon-base/__CEPH_MGR_PACKAGE__

Won't they supersede this file on those releases?

**Comment by leseb** [comment]
@jtlayton you're right, I just forgot about that!

**Pull request merged**
