### PR TITLE
bump to ubi9-minimal

### PR DESCRIPTION
**Pull request by guits**
This adds required changes in order to move to ubi9-minimal
    
Signed-off-by: Guillaume Abrioux <gabrioux@redhat.com>

Fixes: #2008

### CODE REVIEW

**Comment by ktdreyer** [comment]
Please change `rhel-8` in `ceph-releases/ALL/ubi9-minimal/daemon-base/content_sets.yml` to `rhel-9`

**Comment by ktdreyer** [comment]
GitHub says there are conflicts - mind rebasing?

I plan to get some downstream RPMs available so that we can test this out locally ahead of merging.

**Comment by guits** [comment]
jenkins test ceph_ansible-all_daemons

**Comment by guits** [comment]
jenkins test ceph_ansible-collocation

**Pull request merged**
