### PR TITLE
Changes for CentOS 9 containers

### PR DESCRIPTION
**Pull request by dmick**
Description of your changes:

Which issue is resolved by this Pull Request:
Resolves #

Checklist:
- [ ] Documentation has been updated, if necessary.
- [ ] Pending release notes updated with breaking and/or notable changes, if necessary.

### CODE REVIEW

**Comment by dmick** [comment]
apparently there are separate files for arm64.  yay.  I'll come in again.

**Comment by ktdreyer** [comment]
@dmick is this ready to merge now?

**Comment by dmick** [comment]
No, I've been distracted by other fires and haven't yet done the arm64 changes.  Fires out, I can get to this next

**Comment by dmick** [comment]
Passing tests here at least now.  the sloppy bash/python test failures are about docker.io pull ratelimiting.  I'm not happy about that.

**Comment by dmick** [comment]
jenkins lint

**Comment by dmick** [comment]
jenkins lint

**Comment by dmick** [comment]
jenkins flake8

**Comment by dmick** [comment]
rebased.  @guits, please have a look; you're the only one I know who has a chance of catching stupid errors.

**Comment by guits** [comment]
@dmick shouldn't we change the defaults?

```diff
diff --git a/Makefile b/Makefile
index 6f65469c..d458b227 100644
--- a/Makefile
+++ b/Makefile
@@ -21,7 +21,8 @@ FLAVORS ?= \
        pacific,centos,8 \
        quincy,centos,8 \
        reef,centos,8 \
-       main,centos,8
+       squid,centos,9 \
+       main,centos,9

 TAG_REGISTRY ?= ceph

```

**Review by guits — APPROVED** [review]
> I'm planning on doing that with a followup, once we get some experience with building/testing on c9. It's a larger decision.

alright.

then it looks good, at least, i don't see anything obvious. let's merge and address issues if any with a follow up PR.

**Comment by cbodley** [comment]
are we ready to add this containerization step to our centos9 jenkins builds?

**Pull request merged**
