### PR TITLE
Add ubuntu ceph-release

### PR DESCRIPTION
**Pull request by albzha**
Description of your changes:
Add Ubuntu 20.04 Focal ceph-release (Octopus).

Which issue is resolved by this Pull Request:
Following on issue [#1994](https://github.com/ceph/ceph-container/issues/1994)

I created the ubuntu ceph-release folder based on the debian release and made the necessary changes to be able to use an Ubuntu base image. Currently, I have only tested it with an Ubuntu focal image with Ceph octopus version. I tried a basic ceph-ansible containerized deployment and it worked well.

Points to note:
- ceph-grafana-dashboard package wasn't available on focal, but was available on impish. Since it was only composed of json, I added it directly in the focal folder to add them in the image directly.
- libstoragemgmt package wasn't available either, it was last available on Ubuntu xenial. I saw their github and it is possible to build the image from the source but I'm not too sure about what the best practice is to add it to the image.  

For anyone who wants to test this image, to build it just run this command in the root folder of the repository:
make FLAVORS=octopus,ubuntu,focal build

Any feedback is appreciated.

### CODE REVIEW

**Comment by guits** [comment]
@albzha  I'm sorry but I think this is unlikely that this PR gets merged.
Even though nothing has been decided yet, I think the plan is going to build CentOS-based container image only.

**Comment by zhongzhoucai** [comment]
> @albzha I'm sorry but I think this is unlikely that this PR gets merged. Even though nothing has been decided yet, I think the plan is going to build CentOS-based container image only.

@guits Can I ask why we are building CentOS-based container image only?

**Comment by guits** [comment]
> > @albzha I'm sorry but I think this is unlikely that this PR gets merged. Even though nothing has been decided yet, I think the plan is going to build CentOS-based container image only.
> 
> @guits Can I ask why we are building CentOS-based container image only?

In my opinion, in a 'container mindset', what you should care about is the application you are running in your container, not the OS it's running on. Here you want Ceph running in a container, which is what you will get. Why would you care about the underlying OS? I'm not saying there's definitely no reason, but in my opinion, it shouldn't be your main concern.

Supporting multiple distros was definitely a burden for this project, by the way, this has been broken for a while and almost nobody noticed it.

**Comment by zhongzhoucai** [comment]
@guits I'm building a FIPS compliant ceph image, and I'm interested in ubuntu based image because it has been FIPS 140-2 validated and listed [here](https://csrc.nist.gov/projects/cryptographic-module-validation-program/validated-modules/search/all), while centos is not part of that list. So I assume it's simpler to turn on FIPS mode in ubuntu, but I'm not sure if that's possible in centos-based images.

**Comment by zhongzhoucai** [comment]
@albzha I used rook-ceph to install ceph on top of ubuntu using this PR, but osd and mon are crashlooping due to `Liveness probe failed: admin_socket: exception getting command descriptions: [Errno 2] No such file or directory`. And I see the log entries in mon log:
`warning: unable to create /var/run/ceph: (13) Permission denied`
`debug 2022-08-05T00:38:06.472+0000 7f0960c2c540 -1 asok(0x56213ef7e000) AdminSocketConfigObs::init: failed: AdminSocket::bind_and_listen: failed to bind the UNIX domain socket to '/var/run/ceph/ceph-mon.a.asok': (2) No such file or directory`

That seems to be the reason liveness probe failed.

**Comment by ktdreyer** [comment]
For FIPS on CentOS, you can run

```
fips-mode-setup --enable
```

To check the current status, run:

```
fips-mode-setup --check
```

See `man fips-mode-setup` for more information. Please test this on a non-production system before doing this live on your production Ceph clusters!

This PR uses Octopus, which is EOL. Also we'll [require Ubuntu Jammy soon](https://lists.ceph.io/hyperkitty/list/dev@ceph.io/thread/KSHR4QS5X6EMC5V4DTJUJJ4464LX5BPV/#YL7YXVL3IK6L2X6H6GPI6L4JKYIWOJXP), and this PR uses Ubuntu Focal.

**Pull request closed without merging**
