### PR TITLE
daemon-base/Makefile: chown $(USER) $(DAEMON_BASE_IMAGE)

### PR DESCRIPTION
**Pull request by tchaikov**
https://tracker.ceph.com/issues/44250
Signed-off-by: Kefu Chai <tchaikov@gmail.com>

Description of your changes:

Which issue is resolved by this Pull Request:
Resolves #

Checklist:
- [ ] Documentation has been updated, if necessary.
- [ ] Pending release notes updated with breaking and/or notable changes, if necessary.

### CODE REVIEW

**Comment by tchaikov** [comment]
travis-ci/pr failed due to copr outage: https://pagure.io/fedora-infrastructure/issue/8668

**Comment by dsavineau** [comment]
I'm sick of this kind of changes.
Now the Travis CI is broken [1], the upstream build system (which includes the `-devel` tags) [2][3] and the downstream build system are broken.

You're only doing changes (workaround as you said) for your container CI (ceph-ci) without understanding how the ceph-container projet is working.

> travis-ci/pr failed due to copr outage: https://pagure.io/fedora-infrastructure/issue/8668

You're only looking at 1/4 of the jobs. All stable relases aren't using the copr infrastructure. So if you had took a look to the other jobs then you should have seen that the change is breaking everything for daemon container image.

Also the context (commit body and PR description) is useless. You're talking about doing chown stuff but you're removing container image which is unrelated to the subject.

That's the same thing for https://github.com/ceph/ceph-container/pull/1594. What have changed on the ceph-ci CI side recently to explain this ? AFAIK the ceph-ci CI was already using podman and multiple rpm packages have groupadd/useradd command in installation scripts.

[1] https://travis-ci.org/ceph/ceph-container/builds/653978586
[2] https://2.jenkins.ceph.com/job/ceph-container-build-push-imgs/128/
[3] https://2.jenkins.ceph.com/job/ceph-container-build-push-imgs-devel-nightly/234/

**Comment by tchaikov** [comment]
@dsavineau yes, i didn't want to pretend that i understand this project. if the change does not help please feel free to revert it. i did this to merely to address the failure caused by https://bugzilla.redhat.com/show_bug.cgi?id=1802907. because podman does not allow us to change the owner of an image, "chown" is just a metaphor. the reason i mentioned the copr issue just was to provide information not to explain every failure.

> AFAIK the ceph-ci CI was already using podman and multiple rpm packages have groupadd/useradd command in installation scripts.

i think you guys understand podman better than i do. so if reverting this change is able to address the "groupadd" issue. again, please feel free to do so.

**Comment by liewegas** [comment]
If do you revert, please time it when you are available to address the original issue if it reoccurs. We went from failing 10-20% of runs at the beginning of last week to failing ~100% of them.  See https://tracker.ceph.com/issues/44242

**Comment by tchaikov** [comment]
> What have changed on the ceph-ci CI side recently to explain this ? AFAIK the ceph-ci CI was already using podman and multiple rpm packages have groupadd/useradd command in installation scripts.

i think it's a kernel issue in kernel-4.18 shipped by RHEL/CentOS 8.1, as the referenced bugzilla ticket points out. i am not sure what `ceph-ci` CI stands for. if you could point me to a link, that'd be great.

**Comment by tchaikov** [comment]
i am sorry for breaking the build.

**Comment by guits** [comment]
> @dsavineau yes, i didn't want to pretend that i understand this project.

IMO, I think this is why we usually wait for a review of the main maintainers before merging PR in a project.

We've already pointed this out [here](https://github.com/ceph/ceph-container/pull/1551#issuecomment-567609508) but it looks like it had no effect...

**Comment by liewegas** [comment]
> > @dsavineau yes, i didn't want to pretend that i understand this project.
> 
> IMO, I think this is why we usually wait for a review of the main maintainers before merging PR in a project.
> 
> We've already pointed this out [here](https://github.com/ceph/ceph-container/pull/1551#issuecomment-567609508) but it looks like it had no effect...

Normally, yes.  The problem is that 3 days is a long time to wait for a fix when, from where we're sitting, ceph-container is already 100% broken (no builds are completing and our ability to test and merge code is completely halted).  Are there other consumers of new container builds that we broken in the process?  My understanding is that containers are built for existing release tags and for latest-master-devel, so users of the latter would be the only ones impacted by any additional regression?

**Comment by liewegas** [comment]
I'm sorry we broke the build.  I did not realize it could impact anyone that wasn't already impacted, and I thought I saw a reference to the same failures already existing without kefu's patch.  :(  We should consider ways to allow us to unbreak the CI without impacting anyone else...

**Pull request merged**
