### PR TITLE
daemon-base: add ceph-volume package if CEPH_POINT_RELEASE>=17

### PR DESCRIPTION
**Pull request by tchaikov**
Description of your changes:

Which issue is resolved by this Pull Request:
Resolves #

Checklist:
- [ ] Documentation has been updated, if necessary.
- [ ] Pending release notes updated with breaking and/or notable changes, if necessary.

### CODE REVIEW

**Comment by tchaikov** [comment]
this change depends on https://github.com/ceph/ceph/pull/42465

**Comment by tchaikov** [comment]
@dsavineau @guits ping?

**Comment by tchaikov** [comment]
@dsavineau @guits ping?

**Comment by tchaikov** [comment]
@dsavineau @guits ping?

**Comment by tchaikov** [comment]
@dsavineau @guits ping?

**Comment by guits** [comment]
jenkins test ceph_ansible-lvm_osds

**Comment by guits** [comment]
jenkins test lvm_osds

**Review by guits — APPROVED** [review]

**Comment by guits** [comment]
sorry for the delay @tchaikov

**Pull request merged**
