### PR TITLE
Test Nautilus stable build

### PR DESCRIPTION
**Pull request by leseb**
This PR only monitors whether or not we are ready to build a Nautilus RC image.

### CODE REVIEW

**Comment by leseb** [comment]
@jtlayton @ajarr when are we going to have Nautilus packages for Ganesha?
I don't see anything here http://download.ceph.com/nfs-ganesha/rpm-V2.7-stable/ yet.

Thanks.

**Comment by jtlayton** [comment]
Good question. I think those are generated using the nfs-ganesha-stable builds on jenkins:

https://jenkins.ceph.com/view/all/job/nfs-ganesha-stable/

I'm not at all sure who maintains that though -- I'll see if I can hunt them down.

**Comment by leseb** [comment]
@jtlayton thanks, appreciate that.

**Comment by jtlayton** [comment]
The ganesha packages should be there now. The only caveat is that they don't have support for one of the config options that rook sets in the config file and so may not work for nfs server deployments. Once ganesha v2.8 ships though, we should be good to go there.

**Comment by jtlayton** [comment]
retest this please

**Comment by leseb** [comment]
Latest error:

```
Total download size: 127 M
Installed size: 426 M
Downloading packages:
http://download.ceph.com/nfs-ganesha/rpm-V2.7-stable/nautilus/x86_64/libntirpc-1.7.2-0.1.el7.x86_64.rpm: [Errno -1] Package does not match intended download. Suggestion: run yum --enablerepo=ganesha clean metadata
Trying other mirror.
http://download.ceph.com/nfs-ganesha/rpm-V2.7-stable/nautilus/x86_64/nfs-ganesha-2.7.2-0.1.el7.x86_64.rpm: [Errno -1] Package does not match intended download. Suggestion: run yum --enablerepo=ganesha clean metadata
Trying other mirror.
http://download.ceph.com/nfs-ganesha/rpm-V2.7-stable/nautilus/x86_64/nfs-ganesha-rados-grace-2.7.2-0.1.el7.x86_64.rpm: [Errno 14] curl#63 - "Callback aborted"
Trying other mirror.
http://download.ceph.com/nfs-ganesha/rpm-V2.7-stable/nautilus/x86_64/nfs-ganesha-ceph-2.7.2-0.1.el7.x86_64.rpm: [Errno -1] Package does not match intended download. Suggestion: run yum --enablerepo=ganesha clean metadata
Trying other mirror.
http://download.ceph.com/nfs-ganesha/rpm-V2.7-stable/nautilus/x86_64/nfs-ganesha-rgw-2.7.2-0.1.el7.x86_64.rpm: [Errno -1] Package does not match intended download. Suggestion: run yum --enablerepo=ganesha clean metadata
Trying other mirror.
Error downloading packages:
  nfs-ganesha-ceph-2.7.2-0.1.el7.x86_64: [Errno 256] No more mirrors to try.
  libntirpc-1.7.2-0.1.el7.x86_64: [Errno 256] No more mirrors to try.
  nfs-ganesha-2.7.2-0.1.el7.x86_64: [Errno 256] No more mirrors to try.
  nfs-ganesha-rados-grace-2.7.2-0.1.el7.x86_64: [Errno 256] No more mirrors to try.
  nfs-ganesha-rgw-2.7.2-0.1.el7.x86_64: [Errno 256] No more mirrors to try.
```

**Comment by jtlayton** [comment]
Huh, I think that usually means that yum's metadata is out of sync with reality.

Did any of the docker container layers come out of a cache? I have in the past hit problems like this with docker builds when there are leftover layers that were prebuilt from the same hashes, and the upstream repos have changed.

**Comment by leseb** [comment]
@jtlayton each new build from Travis is a new VM you shouldn't have this problem. Just to be sure I pushed a change to retrigger the build without hitting the "build" button again but same problem in the end :/

**Comment by jtlayton** [comment]
Ahh, I think the problem is the repo metadata on download.ceph.com. It seems to have the wrong hashes in it? The packages all have a mod time of "28-Feb-2019 23:58 ", but the repodata files have mod times of "28-Feb-2019 11:40".

We probably need to ask tserlin to regenerate the repo metadata there?

**Comment by leseb** [comment]
@tserlin FYI :)

**Comment by leseb** [comment]
Need to monitor http://download.ceph.com/rpm-nautilus/el7/aarch64/

**Pull request closed without merging**
