### PR TITLE
daemon-base: drop ceph-mgr-ssh, except for the master/wip-* special case

### PR DESCRIPTION
**Pull request by liewegas**
This is an ugly kludge but it will work for the time being until something
more elegant is sorted out.

Signed-off-by: Sage Weil <sage@redhat.com>

### CODE REVIEW

**Comment by liewegas** [comment]
alternative to #1533 

this is a quick hack until we do a bigger cleanup...

**Comment by liewegas** [comment]
retest this please

**Comment by leseb** [comment]
I restarted the job since:

```
No package ceph-mgr-cephadm available.
[91mError: Nothing to do
```

**Comment by leseb** [comment]
Better on the second run!

```
Installed:
  ceph-mgr-cephadm.noarch 2:15.0.0-8339.gcb399a9.el7   
```

**Pull request merged**
