### PR TITLE
tests: update ci testing

### PR DESCRIPTION
**Pull request by guits**
CI testing is now broken for a while.
This commit is intended for fixing the CI.

Signed-off-by: Guillaume Abrioux <gabrioux@redhat.com>

### CODE REVIEW

**Comment by guits** [comment]
jenkins test ceph_ansible-nautilus-centos7-all_daemons

**Comment by guits** [comment]
jenkins test ceph_ansible-nautilus-centos7-all_daemons

**Comment by guits** [comment]
jenkins test ceph_ansible-lvm_osds

**Comment by guits** [comment]
jenkins test ceph_ansible-lvm_osds

**Comment by guits** [comment]
jenkins test ceph_ansible-lvm_osds

**Comment by guits** [comment]
jenkins test ceph_ansible-lvm_osds

**Comment by guits** [comment]
jenkins test ceph_ansible-lvm_osds

**Comment by tchaikov** [comment]
```
  - nothing provides python3-cherrypy needed by ceph-mgr-modules-core-2:15.1.0-1106.g52a4256.el8.noarch
573  - nothing provides python3-pecan needed by ceph-mgr-modules-core-2:15.1.0-1106.g52a4256.el8.noarch
574
```

@guits  travis-ci/pr failed due to copr outage: https://pagure.io/fedora-infrastructure/issue/8668

**Comment by guits** [comment]
@tchaikov thanks for pointing this out

**Comment by guits** [comment]
jenkins test ceph_ansible-lvm_osds

**Comment by guits** [comment]
jenkins test ceph_ansible-lvm_osds

**Comment by guits** [comment]
jenkins test ceph_ansible-lvm_osds

**Comment by guits** [comment]
jenkins test ceph_ansible-lvm_osds

**Comment by guits** [comment]
jenkins test ceph_ansible-lvm_osds

**Pull request merged**
