### PR TITLE
contrib/build-push-ceph-container-imgs.sh: workaround podman-docker

### PR DESCRIPTION
**Pull request by liewegas**
Signed-off-by: Sage Weil <sage@redhat.com>

### CODE REVIEW

**Comment by dsavineau** [comment]
Thanks for merging this without a clean CI state and with a change that doesn't make sense at all.

- `|| true` is a horrible solution.
- Does it make sense to call the `install_docker` function on CentOS 8 ? **no**, instead we should do a smarter thing and install `podman` if we're not using docker.

**Comment by liewegas** [comment]
We're trying to unbreak the ceph qa before shutdown and || true was the safest possible patch that could address the problem without breaking anything that was previously working.

If you could join #sepia on irc.oftc.net it'll be much easier to coordinate!

**Comment by guits** [comment]
would be nice if you guys could ask for reviews in github anyway before merging like this

**Comment by djgalloway** [comment]
It didn't work anyway :disappointed:

```
+ sudo yum install -y docker

Repository apt-mirror.front.sepia.ceph.com_lab-extras_8_ is listed more than once in the configuration
Last metadata expiration check: 2:04:23 ago on Thu Dec 19 16:30:21 2019.

Dependencies resolved.
================================================================================
 Package  Arch   Version                                        Repository
                                                                           Size
================================================================================
Installing:
 podman-docker
          noarch 1.0.5-1.gitf604175.module_el8.0.0+194+ac560166 AppStream  28 k
Upgrading:
 podman   x86_64 1.0.5-1.gitf604175.module_el8.0.0+194+ac560166 AppStream 9.1 M

Transaction Summary
================================================================================
Install  1 Package
Upgrade  1 Package

Total download size: 9.1 M
Downloading Packages:

(1/2): podman-docker-1.0.5-1.gitf604175.module_  83 kB/s |  28 kB     00:00    
(2/2): podman-1.0.5-1.gitf604175.module_el8.0.0  13 MB/s | 9.1 MB     00:00    
--------------------------------------------------------------------------------
Total                                           4.7 MB/s | 9.1 MB     00:01     

Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Preparing        :                                                        1/1 

  Running scriptlet: podman-1.0.5-1.gitf604175.module_el8.0.0+194+ac56016   1/1 
  Upgrading        : podman-1.0.5-1.gitf604175.module_el8.0.0+194+ac56016   1/3 
  Installing       : podman-docker-1.0.5-1.gitf604175.module_el8.0.0+194+   2/3 
  Cleanup          : podman-1.0.0-2.git921f98f.module_el8.0.0+58+91b614e7   3/3 

  Running scriptlet: podman-1.0.0-2.git921f98f.module_el8.0.0+58+91b614e7   3/3 
  Verifying        : podman-docker-1.0.5-1.gitf604175.module_el8.0.0+194+   1/3 
  Verifying        : podman-1.0.5-1.gitf604175.module_el8.0.0+194+ac56016   2/3 
  Verifying        : podman-1.0.0-2.git921f98f.module_el8.0.0+58+91b614e7   3/3 

Upgraded:
  podman-1.0.5-1.gitf604175.module_el8.0.0+194+ac560166.x86_64                  

Installed:
  podman-docker-1.0.5-1.gitf604175.module_el8.0.0+194+ac560166.noarch           

Complete!

+ sudo systemctl start docker
Failed to start docker.service: Unit docker.service not found.
+ /bin/true
```

**Comment by liewegas** [comment]
> would be nice if you guys could ask for reviews in github anyway before merging like this

Yeah, definitely--very sorry about that!

**Pull request merged**
