### PR TITLE
Fix mon id where name in monmap doesn't match monitor name

### PR DESCRIPTION
**Pull request by JrCs**
This fix change the mon id in monmap in case the monitor name in the monmap doesn't match the hostname of the monitor. 
This can be the case when using k8s to create the monmap from the pods labels and the hostname of the monitors are full qualified while the hostname of the servers is not full qualified.

### CODE REVIEW

**Comment by Raboo** [comment]
Can you make it so it works with jewel as well?

**Comment by leseb** [comment]
@JrCs, @Raboo please reach an agreement when it comes to who/how this should be fixed but please for both Jewel and Luminous :). Thanks

**Comment by JrCs** [comment]
Backport to jewel too.

**Comment by Raboo** [comment]
Thanks @JrCs

**Pull request merged**
