### PR TITLE
Sree: support python3

### PR DESCRIPTION
**Pull request by dsavineau**
The Sree interface wasn't compatible with python3. Thoses changes allow
to run sree on both python 2 and 3.
This was breaking ceph nano (cn) with the CentOS 8 based ceph container
images (like master/octopus).

Multiple changes have been made to Sree to implement the python 3 suport
available in v0.2 [1]

The Sree tarball has been updated and the older one (v0.1) removed. Also
the SREE_VERSION variable in the travis configuration has been removed
because this wasn't used.

Signed-off-by: Dimitri Savineau <dsavinea@redhat.com>

### CODE REVIEW

**Comment by dsavineau** [comment]
I just discovered that the Sree source was coming from your own fork.
I've updated the tarball (untar, modify, tar) but it's maybe better to add the changes on your repository. WDYT ?

**Comment by leseb** [comment]
> I just discovered that the Sree source was coming from your own fork.
> I've updated the tarball (untar, modify, tar) but it's maybe better to add the changes on your repository. WDYT ?

Yes because I made many changes in the interface.
Yes, do you mind sending your changes as a PR in my fork?

Thanks.

**Comment by dsavineau** [comment]
> > I just discovered that the Sree source was coming from your own fork.
> > I've updated the tarball (untar, modify, tar) but it's maybe better to add the changes on your repository. WDYT ?
> 
> Yes because I made many changes in the interface.
> Yes, do you mind sending your changes as a PR in my fork?
> 
> Thanks.

Yes sure I'll do that

**Comment by dsavineau** [comment]
@leseb Since https://github.com/leseb/Sree/pull/3 is merged, should we create a new release on https://github.com/leseb/Sree and import it into ceph-container ?

**Comment by leseb** [comment]
> @leseb Since [leseb/Sree#3](https://github.com/leseb/Sree/pull/3) is merged, should we create a new release on https://github.com/leseb/Sree and import it into ceph-container ?

Yes! Done https://github.com/leseb/Sree/releases/tag/v0.2

**Comment by dsavineau** [comment]
Great I'll update this PR with the new tarball

**Comment by dsavineau** [comment]
@leseb does this look good to you ?

**Pull request merged**
