### PR TITLE
rhel7: add ppc64le content sets

### PR DESCRIPTION
**Pull request by yselkowitz**
Signed-off-by: Yaakov Selkowitz <yselkowi@redhat.com>

Description of your changes:
Allow building rhel7 container on ppc64le.

Checklist:
- [ n/a ] Documentation has been updated, if necessary.
- [ n/a ] Pending release notes updated with breaking and/or notable changes, if necessary.

### CODE REVIEW

**Comment by leseb** [comment]
@yselkowitz are you going to do the sync downstream too?

**Comment by yselkowitz** [comment]
I can work with @ktdreyer on merging downstream.

**Comment by leseb** [comment]
@yselkowitz please use https://github.com/ceph/ceph-container/blob/master/contrib/compose-rhcs.sh and https://github.com/ceph/ceph-container/blob/master/contrib/commit-rhcs.sh to do the backport. Thanks

**Comment by yselkowitz** [comment]
IIUC, we need to get this commit into stable-3.2 first, what is the procedure for that?

**Comment by leseb** [comment]
@yselkowitz backport this commit into stable-3.2 branch.

**Pull request merged**
