### PR TITLE
squid/ubi9-ibm: install libcephfs-daemon

### PR DESCRIPTION
**Pull request by andrewschoen**
Fixes: #2240

### CODE REVIEW

**Comment by andrewschoen** [comment]
@guits I saw that `ceph-mgr-callhome` is included here already https://github.com/ceph/ceph-container/blob/main/ceph-releases/ALL/ubi9-ibm/daemon-base/__CEPH_IBM_PACKAGES__#L1

I wasn't sure if that would be inherited in the squid specific __CEPH_IBM_PACKAGES__ file though. Do I need to duplicate that install or can I just inlude `libcephs-daemon` here for squid?

**Comment by phlogistonjohn** [comment]
This change is currently only for ibm ceph. Ideally, we will get it upstream too but it will take longer (AFAIK). So assume this is ibm only.

**Comment by andrewschoen** [comment]
> @andrewschoen is this package supposed to be included only for ceph ibm? if yes, then that change looks good to me

yes, for now this is IBM only.

**Comment by ktdreyer** [comment]
@phlogistonjohn there's a PR for this in upstream ceph, right? Could you link to that here?

**Comment by andrewschoen** [comment]
> @phlogistonjohn there's a PR for this in upstream ceph, right? Could you link to that here?

@ktdreyer I included some info about the upstream work in the issue I created: https://github.com/ceph/ceph-container/issues/2240

I think this is the upstream PR that includes `libcephfs-daemon`: https://github.com/ceph/ceph/pull/58376

**Pull request closed without merging**
