### PR TITLE
src/daemon: remove ceph-disk support

### PR DESCRIPTION
**Pull request by dsavineau**
In nautilus, ceph-disk isn't present anymore so some OSD scenarios
aren't usefull anymore.

Signed-off-by: Dimitri Savineau <dsavinea@redhat.com>

### CODE REVIEW

**Comment by AndrewwHummer** [comment]
Is there an replacement for ceph-disk prepare planned on ceph-volume basis?

**Comment by dsavineau** [comment]
> Is there an replacement for ceph-disk prepare planned on ceph-volume basis?

It's not planned for now

**Comment by cbrherms** [comment]
How would one prepare disks / osds with this feature not currently implemented when working with nautilus?

**Comment by AndrewwHummer** [comment]
> How would one prepare disks / osds with this feature not currently implemented when working with nautilus?

This! I am pulling my hairs out because of this problem... I guess I will open an issue soon and ask for adivce

**Comment by dsavineau** [comment]
> How would one prepare disks / osds with this feature not currently implemented when working with nautilus?

```console
# docker run --rm --privileged --net=host --ipc=host --ulimit nofile=1024:4096 -v /run/lock/lvm:/run/lock/lvm:z -v /var/run/udev/:/var/run/udev/:z -v /dev:/dev -v /etc/ceph:/etc/ceph:z -v /run/lvm/:/run/lvm/ -v /var/lib/ceph/:/var/lib/ceph/:z -v /var/log/ceph/:/var/log/ceph/:z --entrypoint=ceph-volume docker.io/ceph/daemon:latest-nautilus lvm prepare ....
```

With the right configuration from [1]

[1] https://docs.ceph.com/docs/master/ceph-volume/lvm/prepare/

**Comment by caisan** [comment]
hi, all. Could anyone tell me that even ceph-disk is not supported from N anymore. WHY ceph-container still use the ceph-disk in `osd_disk_prepare.sh` (in ceph/daemon:latest also)? why?

**Comment by archef2000** [comment]
This problem still exists why is it not merged?

**Comment by archef2000** [comment]
@guits Mind having a look at this?

**Comment by archef2000** [comment]
Bump

**Comment by archef2000** [comment]
@ktdreyer Why is this not merged yet?

**Comment by archef2000** [comment]
bump

**Comment by archef2000** [comment]
bump

**Comment by archef2000** [comment]
bump

**Comment by guits** [comment]
@archef2000 what's the actual issue?

**Comment by archef2000** [comment]
When I run the container on the latest release or 1-2 versions older I can't init the disk as it is missing the ceph-disk command.

**Comment by guits** [comment]
> When I run the container on the latest release or 1-2 versions older I can't init the disk as it is missing the ceph-disk command.

Are you still running ceph-disk prepared OSDs ? Support for ceph-disk was dropped a long time ago, you might want to consider to migrate to ceph-volume at this point.

**Comment by archef2000** [comment]
No I was trying to setup ceph from new (did override the start of each disk after each attempt).
I used docker compose without ansible and everything that I tried I got ceph-disk command not found.
I will try to get it working again and send you the compose file + logs.

**Comment by archef2000** [comment]
Is it solved?

**Pull request closed without merging**
