### PR TITLE
ceph: unblock master images

### PR DESCRIPTION
**Pull request by leseb**
Let's also pin master to ganesha 2.8 since ganesha master is still
broken.

Signed-off-by: Sébastien Han <seb@redhat.com>

### CODE REVIEW

**Comment by guits** [comment]
Although I'm unsure nfs-ganesha 2.8 is supposed to work with ceph@master, I'm merging this so we can build images.

**Comment by guits** [comment]
@dsavineau  ^

**Comment by dsavineau** [comment]
nfs-ganesha 2.8 couldn't be build against ceph@master due to change in the rgw lib.
Even if we're able to install nfs-ganesha 2.8 (nautilus) on ceph@master image, I don't think everything will wok on the ganesha side.

**Comment by guits** [comment]
> nfs-ganesha 2.8 couldn't be build against ceph@master due to change in the rgw lib.
> Even if we're able to install nfs-ganesha 2.8 (nautilus) on ceph@master image, I don't think everything will wok on the ganesha side.

this is well what I was afraid of

**Comment by dsavineau** [comment]
> this is well what I was afraid of

:+1: maggle

**Pull request merged**
