### PR TITLE
add reef release

### PR DESCRIPTION
**Pull request by ljflores**
reef v18.1.0 is now available.

Description of your changes:

Which issue is resolved by this Pull Request:
Resolves #

Checklist:
- [x] Documentation has been updated, if necessary.
- [x] Pending release notes updated with breaking and/or notable changes, if necessary.

### CODE REVIEW

**Comment by ljflores** [comment]
Based on this commit: https://github.com/ceph/ceph-container/commit/cd1c29142fcb004d1935387c047a9bfba6aa015c

**Comment by dmick** [comment]
We need to positively verify that version of nfs-ganesha is appropriate/sanity-tested with reef, and wait for the checks to complete, but otherwise LGTM

**Review by dmick — CHANGES_REQUESTED** [review]
See comments; just verify that nfs-ganesha version before committing.

**Comment by ljflores** [comment]
I can also remove that part for now and we can deal with it later so the RC isn't blocked.

**Comment by dmick** [comment]
No, the question has to be answered and nfs-ganesha has to be included to be a valid container release.  (I've also said many times that this ought to be a process that happens before we have to do the actual release, but it's fallen on deaf ears.)

**Comment by ljflores** [comment]
The x86_64 container build failed. Any suggestions?

**Comment by guits** [comment]
see #2109

**Pull request closed without merging**
