### PR TITLE
Fixing automatic "client_host" creation on etcd

### LINKED ISSUE #901: ceph/daemon:tag-stable-3.0-luminous-centos-7: mon: etcd key /ceph-config/ceph/client_host and uuencode missing
I started with https://github.com/ceph/ceph-container/tree/master/ceph-releases/luminous/centos/7/daemon as cookbook.

Image: CEPH_IMAGE=ceph/daemon:tag-stable-3.0-luminous-centos-7

1. docker run -it ${CEPH_MON} ${CEPH_KV} ${CEPH_IMAGE} populate_kvstore
    was successful:
   2018-02-10 16:56:49  /entrypoint.sh: Adding key /osd/osd_journal_size with value 100 to KV store.
100

2. docker run -it --name ceph-mon ${CEPH_MON} ${CEPH_NET} ${CEPH_VAR} ${CEPH_KV} ${CEPH_IMAGE} mon
failed:
2018-02-10 16:57:22  /entrypoint.sh: 'osd' key already exists
2018-02-10 16:57:22  /entrypoint.sh: Adding Mon Host - myhost.
myip
myhost
Error:  100: Key not found (/ceph-config/ceph/monSetupComplete) [173]
2018-02-10 16:57:23  /entrypoint.sh: No configuration found for cluster ceph. Generating.
eddbd830-978b-44ac-ac8e-698926ee876c
2018-02-10T16:57:23Z myhost /tmp/tmp.yzpanpV4uT/confd[290]: INFO Backend set to etcd
2018-02-10T16:57:23Z myhost /tmp/tmp.yzpanpV4uT/confd[290]: INFO Starting confd
2018-02-10T16:57:23Z myhost /tmp/tmp.yzpanpV4uT/confd[290]: INFO Backend nodes set to http://myip:4001
2018-02-10T16:57:23Z myhost /tmp/tmp.yzpanpV4uT/confd[290]: ERROR 100: Key not found (/ceph-config/ceph/client_host) [174]
2018-02-10 16:57:23  /entrypoint.sh: Waiting for confd to write initial templates...

...

After setting the key (maybe wrong value)
etcdctl -C http://myip:4001 set /ceph-config/dx-cephtest/client_host myhost

and rerun the docker command above it works until:
2018-02-10 17:06:44  /entrypoint.sh: Importing Keyrings and Monmap to KV.
[mon.]
        key = ...
        caps mon = "allow *"

[client.admin]
        key = ...
        auid = 0
        caps mds = "allow"
        caps mgr = "allow *"
        caps mon = "allow *"
        caps osd = "allow *"

/config.kv.etcd.sh: line 87: uuencode: command not found
Error:  value required

I tried the same with the ceph/daemon:tag-stable-3.0-luminous-ubuntu-16.04 image and it works after adding the /ceph-config/dx-cephtest/client_host key.

Edit: CEPH_IMAGE=ceph/daemon:build-master-luminous-centos-7 works for me

### PR DESCRIPTION
**Pull request by flaviostutz**
Description of your changes:

Which issue is resolved by this Pull Request:
Resolves #901

Checklist:
- [X] Documentation has been updated, if necessary.
- [X] Pending release notes updated with breaking and/or notable changes, if necessary.

### CODE REVIEW

**Comment by flaviostutz** [comment]
I've just signed with a new commit. How do I re-run this checks on current PR?

**Comment by leseb** [comment]
@flaviostutz please squash your commits.

**Comment by flaviostutz** [comment]
Sorry. I give up.

**Comment by leseb** [comment]
@flaviostutz no worries, feel free to re-open a PR if it's easier.

**Comment by ErwanAliasr1** [comment]
@flaviostutz can you update the PR ? That would be cool to have it.

**Comment by leseb** [comment]
Closing this since the original committer gave up.

**Pull request closed without merging**
