### PR TITLE
make: revise the meaning of a 'flavor', and allow overrides of BASEOS_ vars - fix #1028

### LINKED ISSUE #1028: BASE_IMAGE is not considered in  DAEMON_BASE_IMAGE & DAEMON_IMAGE
When I build the arm64 code with a BASE_IMAGE override, DAEMON_BASE_IMAGE  & DAEMON_IMAGE consider the real name aka centos-arm64.

If I do force the BASE_IMAGE, it should be kept during the push too unless when I try to push it with the expected name, it fails.

++ make RELEASE=master-0026986 FLAVORS=luminous,centos-arm64,7 BASE_IMAGE=centos:7 push

  CEPH_VERSION      : luminous
  CEPH_POINT_RELEASE: 
  HOST_ARCH         : aarch64
  BASEOS_REGISTRY   : _
  BASEOS_REPO       : centos-arm64
  BASEOS_TAG        : 7
  IMAGES_TO_BUILD   : daemon-base daemon
  STAGING_DIR       : staging/luminous-centos-arm64-7-aarch64
  RELEASE           : master-0026986
  DAEMON_BASE_IMAGE : ceph/daemon-base:master-0026986-luminous-centos-arm64-7-aarch64
  DAEMON_IMAGE      : ceph/daemon:master-0026986-luminous-centos-arm64-7-aarch64

[...]
++ tag=ceph/daemon-base:master-0026986-luminous-centos-7-aarch64
++ docker tag ceph/daemon-base:master-0026986-luminous-centos-7-aarch64 ceph/daemon-base:latest-luminous
Error response from daemon: no such id: ceph/daemon-base:master-0026986-luminous-centos-7-aarch64

### PR DESCRIPTION
**Pull request by BlaineEXE**
It isn't very straightforward for a user that the BASEOS_REPO and
BASEOS_TAG specified in the flavor spec (`<ceph version>[point
release],<baseos repo>, <baseos tag>`) refer to the ceph-container
source directories. Fix this by changing BASEOS_REPO to DISTRO and
BASEOS_TAG to DISTRO_VERSION in the makefile. We still need BASEOS_REPO
and BASEOS_TAG, because we are planning to make these overrideable.    

Since we now are making the flavor clearly ceph-release source path
locations, the user may want to override any of the individual
components, not just BASE_IMAGE as a whole.

We still have BASE_IMAGE which can be used with `__ENV_[BASE_IMAGE]__`,
but BASE_IMAGE is now calculated and set in staging Python code. Since
visual feedback of the value is still valuable, we add a 'Computed:'
section to the staging output with BASE_IMAGE verified in it.

fixes #1028

### CODE REVIEW

**Comment by BlaineEXE** [comment]
### Scenario from #1028:
```
> make FLAVORS=luminous,centos-arm64,7 BASEOS_REPO=centos stage

  CEPH_VERSION      : luminous
  CEPH_POINT_RELEASE:
  DISTRO            : centos-arm64
  DISTRO_VERSION    : 7
  HOST_ARCH         : x86_64
  BASEOS_REGISTRY   :
  BASEOS_REPO       : centos
  BASEOS_TAG        : 7
  IMAGES_TO_BUILD   : daemon-base daemon
  STAGING_DIR       : staging/luminous-centos-7-x86_64
  RELEASE           : make-fix-1028
  DAEMON_BASE_IMAGE : ceph/daemon-base:make-fix-1028-luminous-centos-7-x86_64
  DAEMON_IMAGE      : ceph/daemon:make-fix-1028-luminous-centos-7-x86_64

Computed:
  BASE_IMAGE        : centos:7
```

### Other possible scenarios

I don't know if this build would succeed, but maybe a user wants to build a debian container from ubuntu source.
```
> make FLAVORS=luminous,ubuntu,16.04 BASEOS_REPO=debian BASEOS_TAG=jessie stage

  CEPH_VERSION      : luminous
  CEPH_POINT_RELEASE:
  DISTRO            : ubuntu
  DISTRO_VERSION    : 16.04
  HOST_ARCH         : x86_64
  BASEOS_REGISTRY   :
  BASEOS_REPO       : debian
  BASEOS_TAG        : jessie
  IMAGES_TO_BUILD   : daemon-base daemon
  STAGING_DIR       : staging/luminous-debian-jessie-x86_64
  RELEASE           : make-fix-1028
  DAEMON_BASE_IMAGE : ceph/daemon-base:make-fix-1028-luminous-debian-jessie-x86_64
  DAEMON_IMAGE      : ceph/daemon:make-fix-1028-luminous-debian-jessie-x86_64

Computed:
  BASE_IMAGE        : debian:jessie
```


Or maybe a user just wants to use their own internal repo and version of ubuntu
```
> make FLAVORS=luminous,ubuntu,16.04 BASEOS_REGISTRY=my-internal-registry BASEOS_REPO=my-ubuntu-with-package-fixes stage

  CEPH_VERSION      : luminous
  CEPH_POINT_RELEASE:
  DISTRO            : ubuntu
  DISTRO_VERSION    : 16.04
  HOST_ARCH         : x86_64
  BASEOS_REGISTRY   : my-internal-registry
  BASEOS_REPO       : my-ubuntu-with-package-fixes
  BASEOS_TAG        : 16.04
  IMAGES_TO_BUILD   : daemon-base daemon
  STAGING_DIR       : staging/luminous-my-ubuntu-with-package-fixes-16.04-x86_64
  RELEASE           : make-fix-1028
  DAEMON_BASE_IMAGE : ceph/daemon-base:make-fix-1028-luminous-my-ubuntu-with-package-fixes-16.04-x86_64
  DAEMON_IMAGE      : ceph/daemon:make-fix-1028-luminous-my-ubuntu-with-package-fixes-16.04-x86_64

Computed:
  BASE_IMAGE        : my-internal-registry/my-ubuntu-with-package-fixes:16.04
```

Or maybe in our testing we want to see if Ubuntu 16.04's code will work with 18.04
```
> make FLAVORS=luminous,ubuntu,16.04 BASEOS_TAG=18.04 stage

  CEPH_VERSION      : luminous
  CEPH_POINT_RELEASE:
  DISTRO            : ubuntu
  DISTRO_VERSION    : 16.04
  HOST_ARCH         : x86_64
  BASEOS_REGISTRY   :
  BASEOS_REPO       : ubuntu
  BASEOS_TAG        : 18.04
  IMAGES_TO_BUILD   : daemon-base daemon
  STAGING_DIR       : staging/luminous-ubuntu-18.04-x86_64
  RELEASE           : make-fix-1028
  DAEMON_BASE_IMAGE : ceph/daemon-base:make-fix-1028-luminous-ubuntu-18.04-x86_64
  DAEMON_IMAGE      : ceph/daemon:make-fix-1028-luminous-ubuntu-18.04-x86_64

Computed:
  BASE_IMAGE        : ubuntu:18.04
```

**Comment by ErwanAliasr1** [comment]
I like the proposal but noticed something which confused me.

In this example: 
> make FLAVORS=luminous,centos-arm64,7 BASEOS_REPO=centos stage
>STAGING_DIR       : staging/luminous-centos-7-x86_64

If STAGING_DIR is using the BASEOS_REPO, it means that is conflicting with any other flavor using that which isn't that nice.

I think that STAGING_DIR should used centos-arm64 which is supposed to be unique.

**Comment by BlaineEXE** [comment]
Great catch!

**Comment by BlaineEXE** [comment]
> I like the proposal but noticed something which confused me.
> 
> In this example:
> 
>     make FLAVORS=luminous,centos-arm64,7 BASEOS_REPO=centos stage
>     STAGING_DIR : staging/luminous-centos-7-x86_64
> 
> If STAGING_DIR is using the BASEOS_REPO, it means that is conflicting with any other flavor using that which isn't that nice.
> 
> I think that STAGING_DIR should used centos-arm64 which is supposed to be unique.

I started to go about changing this to source from DISTRO instead, but I realized that there is more intricacy here. When you specify any overrideable variable, you are potentially messing up other flavor builds. If I said `make FLAVORS="luminous,centos-arm64,7 luminous,opensuse,42.3" BASEOS_REPO=centos, then both the centos-arm64 and opensuse builds will use 'centos' as the baseos repo. This isn't a bad thing, but it **is** undocumented, which I should change. (You could still do `make FLAVORS="luminous,centos-arm64,7 luminous,centos,7" BASEOS_REPO=centos build.parallel` and still have success)

The other intricacy is that in staging, if you see the ceph-version, distro, and distro-version used to source the stage (which is good), you have to inspect the stage files to see what base image is used for that stage. This isn't necessarily a bad thing.

**Comment by BlaineEXE** [comment]
@ErwanAliasr1 : Fixed the potential staging issue and updated the makefile help text. In the process, I think I improved the help text as it's written in the Makefile itself substantially.

**Comment by BlaineEXE** [comment]
@leseb and @ErwanAliasr1: FYI: I'll be in India the 27th through the 7th (inclusive).

**Comment by BlaineEXE** [comment]
I think this also supersedes #1020

**Comment by leseb** [comment]
@BlaineEXE should we close #1020 then?

**Pull request merged**
