### PR TITLE
demo: use EXPOSED_IP for RGW_ADDRESS in Sree

### PR DESCRIPTION
**Pull request by clwluvw**
Related to: https://github.com/leseb/Sree/pull/4

Signed-off-by: Seena Fallah <seenafallah@gmail.com>

### CODE REVIEW

**Review by leseb — COMMENTED** [review]
For this to be consumed we would need a new release of Sree here https://github.com/leseb/Sree/releases and also a similar commit as https://github.com/ceph/ceph-container/commit/fd329efc1eaba717dde57806bce3b2f3a8b11946

**Comment by clwluvw** [comment]
> For this to be consumed we would need a new release of Sree here https://github.com/leseb/Sree/releases and also a similar commit as [fd329ef](https://github.com/ceph/ceph-container/commit/fd329efc1eaba717dde57806bce3b2f3a8b11946)

@leseb Would you create a new release in Sree?

**Comment by leseb** [comment]
> > For this to be consumed we would need a new release of Sree here https://github.com/leseb/Sree/releases and also a similar commit as [fd329ef](https://github.com/ceph/ceph-container/commit/fd329efc1eaba717dde57806bce3b2f3a8b11946)
> 
> @leseb Would you create a new release in Sree?

Yes I will if you update here also :)

**Comment by clwluvw** [comment]
> > > For this to be consumed we would need a new release of Sree here https://github.com/leseb/Sree/releases and also a similar commit as [fd329ef](https://github.com/ceph/ceph-container/commit/fd329efc1eaba717dde57806bce3b2f3a8b11946)
> > 
> > 
> > @leseb Would you create a new release in Sree?
> 
> Yes I will if you update here also :)

Sure!

**Comment by clwluvw** [comment]
@leseb PTAL

**Pull request closed without merging**
